app/anime/urls.py
from django.urls import path

from . import views

app_name = "anime"
urlpatterns = [
    path("anime", views.get_fresh_anime, name="anime"),
    path("hidden_anime/<int:pk>", views.hidden_anime, name="hidden_anime"),
]

app/core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("layout.urls")),
    path("", include("news.urls")),
    path("", include("weathers.urls")),
    path("", include("currencies.urls")),
    path("", include("manga.urls")),
    path("", include("vk.urls")),
    path("", include("anime.urls")),
    path("", include("twitch.urls")),
    path("", include("youtube.urls")),
    path("", include("serials.urls")),
    path("", include("torrents.urls")),
    path("", include("hh.urls")),
    path("", include("dashboard.urls")),
]

app/hh/urls.py
from django.urls import path
from . import views

app_name = "hh"
urlpatterns = [
    path("hh", views.get_fresh_hh, name="hh"),
    path("hidden_hh/<int:pk>", views.hidden_hh, name="hidden_hh"),
]

app/layout/urls.py
from django.urls import path
from . import views


app_name = "layout"
urlpatterns = [
    path("", views.layout, name="layout"),
]

app/manga/urls.py
from django.urls import path

from . import views

app_name = "manga"
urlpatterns = [
    path("manga", views.get_manga, name="manga"),
    path("hidden_manga/<int:pk>", views.hidden_manga, name="hidden_manga"),
]

app/news/urls.py
from django.urls import path
from . import views

app_name = "news"
urlpatterns = [
    # домашняя страница
    path("news", views.get_fresh_news, name="news"),
    # path('parse_news', views.parse_news, name='parse_news'),
    path("hiden_news/<int:pk>", views.hidden_news, name="hidden_news"),
    path("delete_news", views.delete_news, name="delete_news"),
]

app/twitch/urls.py
from django.urls import path
from . import views


app_name = "twitch"
urlpatterns = [
    path("twitch", views.streamers_view, name="twitch"),
    path("twitch/channels", views.streamers_api)
]

app/vk/urls.py
from django.urls import path
from . import views


app_name = "vk"
urlpatterns = [
    path("vk", views.vk, name="vk"),
    path("hidden_post/<int:pk>", views.hidden_post, name="hidden_post"),
    path("delete_post", views.delete_post, name="delete_post"),
]

app/anime/models.py
from django.db import models


class Anime(models.Model):
    """Модель аниме"""

    title_anime = models.CharField(
        "Название и серия",
        max_length=128,
    )
    id_anime = models.PositiveIntegerField(
        "ID видео для портала sibnet",
        unique=True
    )
    date_added = models.DateTimeField(auto_now_add=True)
    _is_expired = models.BooleanField(default=False)

    def __str__(self):
        return self.title_anime

    def hidden(pk):
        r = Anime.objects.get(pk=pk)
        r._is_expired = True
        r.save()


class ListAnime(models.Model):
    '''Список анимe в БД, который будет парситься'''
    title = models.CharField(
        "Название",
        max_length=128,
        unique=True,
    )

    def __str__(self):
        return self.title

app/currencies/models.py
from django.db import models


class Currency(models.Model):
    """Модель валюты"""

    currency = models.JSONField("Валюта")

    def __str__(self):
        return self.currency

app/dashboard/models.py
from django.db import models


class Dashboard(models.Model):
    '''Модель информационной панели'''
    title_undetected_anime = models.CharField(
        "Название аниме",
        max_length=128,
        unique=True,
    )
    date_added = models.DateTimeField(
        "Дата обнаружения необнаруженного аниме",
        auto_now_add=True,
    )

    def delete_from_anime_parse_list(k):
        r = Dashboard.objects.get(title_undetected_anime=k)
        r.delete()

app/hh/models.py
from django.db import models


class Hh(models.Model):
    name = models.CharField("Название вакансии", max_length=128)
    salary = models.JSONField("Информация по оплате")
    url_id = models.PositiveIntegerField(
        "ID https://hh.ru/vacancy/...",
        unique=True,
    )
    published = models.CharField("Дата", max_length=32)
    requirement = models.CharField("Подробности", max_length=512)
    _is_expired = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def hidden(pk):
        r = Hh.objects.get(pk=pk)
        r._is_expired = True
        r.save()

app/manga/models.py
from django.db import models


class Manga(models.Model):
    """Манга"""
    name = models.CharField("Название аниме", max_length=128)
    link = models.URLField("Ссылка на аниме", unique=True)
    _is_expired = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def hidden(pk):
        r = Manga.objects.get(pk=pk)
        r._is_expired = True
        r.save()

app/news/models.py
from django.db import models


class New(models.Model):
    """Новости с mail.ru"""

    news = models.TextField("Новость", unique=True)
    link_news = models.URLField("Ссылка на новость")
    date_added = models.DateTimeField(auto_now_add=True)
    _is_expired = models.BooleanField(default=False)

    def __str__(self):
        return self.news

    def hidden(pk):
        r = New.objects.get(pk=pk)
        r._is_expired = True
        r.save()

app/serials/models.py
from django.db import models


class Serial(models.Model):
    title = models.CharField(
        "Название сериала",
        max_length=128,
        unique=True,
    )
    img = models.PositiveIntegerField("ID картинки сериала")
    serial_and_season = models.CharField(
        "Название сериала и сезона",
        max_length=128,
    )
    episode = models.CharField(
        "Количество серий либо сезон полностью",
        max_length=128,
    )
    data = models.DateTimeField(
        "Автоматически созданная дата после загрузки элемента базы",
        auto_now=True,
    )
    _is_expired = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-data',)

    def hidden(pk):
        r = Serial.objects.get(pk=pk)
        r._is_expired = True
        r.save()

    def d_serial(pk):
        r = Serial.objects.get(pk=pk)
        r.delete()

#
#
# Молодой Скала (2 сезон), 7 серия (RuDub)
# Лучший пекарь Британии (6 сезон), сезон полностью
# Зачарованные (2018) (4 сезон), 8 серия
# Легенда, 21 серия (RuDub)
# Нереалити, 5 серия
# Человек, упавший на Землю, 1 серия (LostFilm)

app/torrents/models.py
from django.db import models


class Torrent(models.Model):
    title = models.CharField("Название сериала", max_length=128)
    link = models.PositiveIntegerField("ID на ссылку торрента", unique=True)
    published = models.DateTimeField(
        "Автоматически созданная дата после загрузки элемента базы",
        auto_now_add=True,
    )
    _is_expired = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class ListSerials(models.Model):
    '''Список сериалов в БД, который будет парситься'''
    title = models.CharField(
        "Название",
        max_length=300,
        unique=True,
    )

    def __str__(self):
        return self.title

app/twitch/models.py
from django.db import models


class Twitch_model(models.Model):
    streamer = models.CharField("Канал твича", max_length=32, unique=True)

app/vk/models.py
from django.db import models


class Vk(models.Model):
    """Модель вк"""

    data_post = models.CharField("Дата публикации", max_length=32)
    text_post = models.TextField("Заголовок поста")
    link_post = models.URLField("Ссылка на публикацию", unique=True)
    link_image_post = models.URLField("Ссылка на картинку")
    _is_expired = models.BooleanField(default=False)

    def hidden(pk):
        r = Vk.objects.get(pk=pk)
        r._is_expired = True
        r.save()

app/youtube/models.py
from django.db import models


class Youtube_model(models.Model):
    id_video = models.CharField(
        "ID Видео",
        max_length=16,
        unique=True,
    )
    _is_expired = models.BooleanField(default=False)

    def hidden(pk):
        r = Youtube_model.objects.get(pk=pk)
        r._is_expired = True
        r.save()

app/anime/views.py
from django.shortcuts import render, redirect
from .models import Anime


def get_fresh_anime(request):
    list_anime = list(
        Anime.objects.filter(_is_expired=False).values(
            "title_anime",
            "id_anime",
            "date_added",
            "id",
        ),
    )

    return render(
        request,
        "anime.html",
        {"list_anime": list_anime},
    )


def hidden_anime(request, pk):
    Anime.hidden(pk)
    return redirect("anime:anime")

app/currencies/views.py
from django.shortcuts import render, redirect
from .models import Currency


def currency_parse(request):
    """Выводит данные из модели Currency"""
    currency_last = list(Currency.objects.values())
    return render(
        request,
        "currency.html",
        {"currency_last": currency_last[0]["currency"]},
    )

app/dashboard/views.py
from django.shortcuts import render, redirect
from .models import Dashboard


def get_undetected_anime(request):
    list_undetected_anime = list(
        Dashboard.objects.all().values(
            "title_undetected_anime",
            "date_added",
            "id",
        )
    )
    return render(
        request,
        "dashboard.html",
        {"list_undetected_anime": list_undetected_anime},
    )


# def delete_anime(request, k):
#     Dashboard.delete_from_anime_parse_list(k)
#     return redirect("dashboard:dashboard")

app/hh/views.py
from django.shortcuts import render, redirect
from .models import Hh
import json


def get_fresh_hh(request):
    hh_list = list(
        Hh.objects.filter(_is_expired=False).values(
            "name",
            "salary",
            "url_id",
            "published",
            "requirement",
            "id",
        ),
    )

    def mutate_hh_items(hh_item):
        hh_item["salary"] = json.loads(hh_item["salary"])
        return hh_item

    mapped_hh_list = map(mutate_hh_items, hh_list)
    hh = list(mapped_hh_list)

    return render(
        request,
        "hh.html",
        {"hh_list": hh},
    )


def hidden_hh(request, pk):
    Hh.hidden(pk)
    return redirect("hh:hh")

app/layout/views.py
from django.shortcuts import render


def layout(request):
    return render(request, "layout.html")

app/manga/views.py
from django.shortcuts import render, redirect
from .models import Manga


def get_manga(request):
    """Получает из БД название и ссылку на мангу"""

    name_and_link = list(
        Manga.objects.filter(_is_expired=False).values(
            "name",
            "link",
            "id",
        ),
    )

    return render(
        request,
        "manga.html",
        {
            "name_and_link": name_and_link,
            # "title": name_and_link[0]["name"],
            # "link": name_and_link[0]["link"],
            # "id": name_and_link[0]["id"],
        },
    )


def hidden_manga(request, pk):
    """Функция которая будет скрывать по id manga"""
    # здесь возможно другой метод у класса Vk
    Manga.hidden(pk)
    return redirect("manga:manga")

app/news/views.py
from django.shortcuts import render, redirect
from .models import New


def get_fresh_news(request):
    """Передаёт в переменную список нескрытых новостей из БД"""

    list_news = list(
        New.objects.filter(_is_expired=False).values(
            "news",
            "link_news",
            "date_added",
            "id",
        ),
    )

    return render(
        request,
        "news.html",
        {"list_news": list_news},
    )


def hidden_news(request, pk):
    New.hidden(pk)
    return redirect("news:news")


def delete_news(request):
    New.objects.all().delete()
    return redirect("news:news")

app/serials/views.py
from django.shortcuts import render, redirect
from .models import Serial
from anime.models import ListAnime
from torrents.models import ListSerials


def get_fresh_serials(request):
    serials_list = list(
        Serial.objects.filter(_is_expired=False).values(
            "title",
            "img",
            "data",
            "serial_and_season",
            "episode",
            "id",
        ),
    )
    return render(
        request,
        "serials.html",
        {"serials_list": serials_list},
    )


def hidden_serial(request, pk):
    Serial.hidden(pk)
    return redirect("serials:serials")


def del_serial(request, pk):
    Serial.d_serial(pk)
    return redirect("serials:serials")


def add_anime_parse(request, pk):
    obj = Serial.objects.get(pk=pk).title
    add_obj, created = ListAnime.objects.update_or_create(title=obj)
    return redirect("serials:serials")


def add_torrent(request, pk):
    obj = Serial.objects.get(pk=pk).title
    add_obj, created = ListSerials.objects.update_or_create(title=obj)
    return redirect("serials:serials")

app/torrents/views.py
from django.shortcuts import render, redirect
from .models import Torrent


def get_fresh_torrent(request):
    """Передаёт в переменную список нескрытых новостей из БД"""

    torrents_list = list(
        Torrent.objects.filter(_is_expired=False).values(
            "title",
            "link",
            "published",
            "id",
        ),
    )

    return render(
        request,
        "torrents.html",
        {"torrents_list": torrents_list},
    )


def hidden_torrent(request, pk):
    Torrent.hidden(pk)
    return redirect("torrents:torrents")

app/templates/anime.html
{% extends "layout.html" %}
{% block title %}АНИМЕ{% endblock %}
{% block title_title %}Аниме{% endblock %}

{% block subtitle %}
Источник: <a href="https://naruto-base.su">Naruto-base.su</a>
{% endblock %}

{% block content %}
<div class="tile is-ancestor columns is-multiline">
  {% for k in list_anime %}
  <div class="tile is-parent is-6">
    <article class="tile is-child message is-dark">
      <div class="message-header">
        <div>
          <p>{{ k.title_anime }}</p>
          <p class="is-size-6 has-text-weight-light">{{ k.date_added }}</p>
        </div>
        <div>
          <div class="dropdown is-hoverable is-right">
            <div class="dropdown-trigger">
              <button class="button is-dark has-text-white" aria-haspopup="true" aria-controls="dropdown-menu">
                <span class="icon is-small">
                  <i class="fa-solid fa-ellipsis-vertical"></i>
                </span>
              </button>
            </div>
            <div class="hh dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <a class="dropdown-item has-text-warning"
                  href="{% url 'anime:hidden_anime' pk=k.id %}">
                  <span class="icon is-small">
                    <i class="fas fa-eye-slash"></i>
                  </span>
                  Скрыть
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="message-body p-0">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="100%" height="100%" src="https://video.sibnet.ru/shell.php?videoid={{ k.id_anime }}" frameborder="0"
            allowfullscreen></iframe>
        </figure>
      </div>
    </article>
  </div>
  {% endfor %}
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="ru" class="has-navbar-fixed-top">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="darkreader" content="NO-DARKREADER-PLUGIN">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}НЕВАЖНО{% endblock %}</title>
  <link rel="shortcut icon" type="image/png" href="static/favicon.ico" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
    integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/solid.min.css"
    integrity="sha512-qzgHTQ60z8RJitD5a28/c47in6WlHGuyRvMusdnuWWBB6fZ0DWG/KyfchGSBlLVeqAz+1LzNq+gGZkCSHnSd3g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css"
    integrity="sha512-OivR4OdSsE1onDm/i3J3Hpsm5GmOVvr9r49K3jJ0dnsxVzZgaOJ5MfxEAxCyGrzWozL9uJGKz6un3A7L+redIQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="static/css/global.css">
  <script src="static/js/global.js"></script>
  {% block extra_head %}{% endblock %}
</head>

<body>
  <nav class="navbar is-fixed-top is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="https://twitch.tv/ucsm" target="_blank">
        <img src="static/images/avatar.png">
      </a>
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbar" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item is-hoverable" href="{% url 'layout:layout' %}">
          <span class="icon is-medium">
            <i class="fa-solid fa-house"></i>
          </span>
          <span>
            Главная
          </span>
        </a>
        <a class="navbar-item is-hoverable" href="{% url 'dashboard:dashboard' %}">
          <span class="icon">
            <i class="fa-solid fa-dashboard"></i>
          </span>
          <span>Панель</span>
        </a>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Сервисы
          </a>

          <div class="navbar-dropdown is-boxed">

            <a class="navbar-item" href="http://localhost:5050" target="_blank">
              <span class="icon">
                <i class="fa-solid fa-database"></i>
              </span>
              <span>PgAdmin</span>
            </a>
            <a class="navbar-item" href="http://localhost:5555" target="_blank">
              <span class="icon">
                <i class="fa-solid fa-calendar-days"></i>
              </span>
              <span>Scheduler</span>
            </a>
          </div>
        </div>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            База данных
          </a>

          <div class="navbar-dropdown is-boxed">
            {% for path in model_paths %}
            <a class="navbar-item" href="/admin/{{ path }}" target="_blank">
              {{ path }}
            </a>
            {% endfor %}
          </div>
        </div>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Развлечения
          </a>
          <div class="navbar-dropdown is-boxed">
            <a class="navbar-item" href="{% url 'anime:anime' %}">
              <span class="icon">
                <i class="fa-solid fa-person-praying"></i>
              </span>
              <span>Аниме</span>
            </a>
            <a class="navbar-item" href="{% url 'twitch:twitch' %}">
              <span class="icon-text">
                <span class="icon">
                  <i class="fa-brands fa-twitch"></i>
                </span>
                <span>Twitch</span>
              </span>
            </a>
            <a class="navbar-item" href="{% url 'youtube:youtube' %}">
              <span class="icon-text">
                <span class="icon">
                  <i class="fa-brands fa-youtube"></i>
                </span>
                <span>YouTube</span>
              </span>
            </a>
          </div>
        </div>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Прочее
          </a>
          <div class="navbar-dropdown is-boxed">
            <a class="navbar-item" href="{% url 'news:news' %}">
              <span class="icon">
                <i class="fa-solid fa-newspaper"></i>
              </span>
              <span>Новости</span>
            </a>
            <a class="navbar-item" href="{% url 'weathers:weather' %}">
              <span class="icon">
                <i class="fa-solid fa-cloud-sun"></i>
              </span>
              <span>Погода</span>
            </a>
            <a class="navbar-item" href="{% url 'currencies:currency' %}">
              <span class="icon">
                <i class="fa-solid fa-tenge-sign"></i>
              </span>
              <span>Валюта</span>
            </a>
            <a class="navbar-item" href="{% url 'torrents:torrents' %}">
              <span class="icon">
                <i class="fa-solid fa-network-wired"></i>
              </span>
              <span>Торренты</span>
            </a>
            <a class="navbar-item" href="{% url 'hh:hh' %}">
              <span class="icon">
                <i class="fa-solid fa-person-digging"></i>
              </span>
              <span>Вакансии</span>
            </a>
            <a class="navbar-item" href="{% url 'vk:vk' %}">
              <span class="icon">
                <i class="fa-brands fa-vk"></i>
              </span>
              <span>ВКонтакте</span>
            </a>
            <a class="navbar-item" href="{% url 'serials:serials' %}">
              <span class="icon">
                <i class="fa-solid fa-film"></i>
              </span>
              <span>Сериалы</span>
            </a>
            <a class="navbar-item" href="{% url 'manga:manga' %}">
              <span class="icon">
                <i class="fa-solid fa-book"></i>
              </span>
              <span>Манга</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </nav>

  {% if not request.get_full_path == "/" %}
  <section class="hero is-small is-dark">
    <div class="hero-body">
      <p class="title">
        {% block title_title %}
        {% endblock %}
      </p>
      <p class="subtitle">
        {% block subtitle %}
        {% endblock %}
      </p>
      {% block hero_body %}
      {% endblock %}
    </div>
    <div class="hero-foot">
      <nav class="tabs is-boxed is-fullwidth pl-5 pr-5">
        <div class="container">
          {% block hero_foot %}
          {% endblock %}
        </div>
      </nav>
    </div>
  </section>
  {% endif %}

  <section class="section">
    {% block content %}
    {% endblock %}
  </section>

  <footer class="has-background-dark">
    <div class="content has-text-centered">
      <p class="is-size-3 has-text-danger">I &lt;3 my chat on Twitch</p>
    </div>
  </footer>

  <script src="static/js/disable-dark-reader.js"></script>
</body>

</html>

app/templates/manga.html
{% extends "layout.html" %}
{% block title %}МАНГА{% endblock %}
{% block title_title %}Манга{% endblock %}

{% block subtitle %}
Источник: <a href="https://mangalib.me/">Mangalib.me</a>
{% endblock %}

{% block content %}
<div class="columns is-multiline">
  {% for m in name_and_link %}
  <article class="column message is-dark" style="background-color: transparent;">
    <div class="message-header" style="border-radius: 4px;">
      <p>
        {{ m.name }}
      </p>
      <div style="display: flex; gap: 1rem;">
        <a class="button is-success is-outlined" target="_blank" href="{{ m.link }}">
          <span class="icon is-small">
            <i class="fa-solid fa-arrow-up-right-from-square"></i>
          </span>
        </a>
        <a class="button is-warning is-outlined" href="{% url 'manga:hidden_manga' pk=m.id %}">
          <span class="icon is-small">
            <i class="fas fa-trash"></i>
          </span>
        </a>
      </div>
    </div>
  </article>
  {% endfor %}
</div>
{% endblock %}

app/templates/news.html
{% extends "layout.html" %}
{% block title %}НОВОСТИ{% endblock %}
{% block title_title %}Новости{% endblock %}

{% block subtitle %}
Источник: <a href="https://mail.ru/">Mail.ru</a>
{% endblock %}

{% block hero_foot %}
<ul>
  <li class="is-active">
    <a href="/news">Новое</a>
  </li>
  <li>
    <a href="#">Прочитано</a>
  </li>
  <li>
    <a href="#">Скрытое</a>
  </li>
  <li>
    <a id="delete-button" class="button is-danger" href="{% url 'news:delete_news' %}">
      Очистить новости
    </a>
  </li>
</ul>
{% endblock %}
{% block content %}
<div class="tile is-ancestor columns is-multiline">
  {% for news in list_news %}
  <div class="tile is-parent is-4">
    <article class="tile is-child message is-dark">
      <div class="message-header">
        <p>
          {{ news.id }}. {{ news.date_added }}
        </p>
        <div>
          <div class="dropdown is-hoverable is-right">
            <div class="dropdown-trigger">
              <button class="button is-dark has-text-white" aria-haspopup="true" aria-controls="dropdown-menu">
                <span class="icon is-small">
                  <i class="fa-solid fa-ellipsis-vertical"></i>
                </span>
              </button>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <a class="dropdown-item has-text-link" href="{{ news.link_news }}" target="_blank">
                  <span class="icon is-small">
                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                  </span>
                  Перейти на новость
                </a>
                <hr class="dropdown-divider">
                <a class="dropdown-item has-text-warning" href="{% url 'news:hidden_news' pk=news.id %}">
                  <span class="icon is-small">
                    <i class="fas fa-eye-slash"></i>
                  </span>
                  Скрыть
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="message-body">
        {{ news.news }}
      </div>
    </article>
  </div>
  {% endfor %}
</div>
{% endblock %}

app/templates/twitch.html
{% extends "layout.html" %}
{% block title %}TWITCH{% endblock %}
{% block title_title %}Стримы{% endblock %}

{% block subtitle %}
Источник: <a href="https://www.twitch.tv/">Twitch.tv</a>
{% endblock %}

{% block content %}
{% csrf_token %}
<div id="twitch" class="columns is-multiline"></div>
<script src="https://embed.twitch.tv/embed/v1.js"></script>
{% load static %}
<script src="static/js/twitch.js"></script>
{% endblock %}

app/templates/vk.html
{% extends "layout.html" %}
{% block title %}ПОСТЫ ВК{% endblock %}
{% block title_title %}Лента ВКонтакте{% endblock %}

{% block subtitle %}
Источник: <a href="https://vk.com/basherbalance">Vk.com</a>
{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="static/css/vk.css">
{% endblock%}

{% block hero_foot %}
<ul>
  <li class="is-active">
    <a href="/vk">Новое</a>
  </li>
  <li>
    <a href="#">Прочитано</a>
  </li>
  <li>
    <a href="#">Скрытое</a>
  </li>
  <li>
    <a id="delete-button" class="button is-danger" href="{% url 'vk:delete_post' %}">
      Очистить ленту
    </a>
  </li>
</ul>
{% endblock %}

{% block content %}
<div class="tile is-ancestor columns is-multiline">
  {% for k in list_post_vk %}
  <div class="tile is-parent is-4">
    <article class="tile is-child message is-dark">
      <div class="message-header">
        <p>{{ k.data_post }}</p>
        <div>
          <div class="dropdown is-hoverable is-right">
            <div class="dropdown-trigger">
              <button class="button is-dark has-text-white" aria-haspopup="true" aria-controls="dropdown-menu">
                <span class="icon is-small">
                  <i class="fa-solid fa-ellipsis-vertical"></i>
                </span>
              </button>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <a class="dropdown-item has-text-link" href="{{ k.link_post }}" target="_blank">
                  <span class="icon is-small">
                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                  </span>
                  Перейти на пост
                </a>
                <hr class="dropdown-divider">
                <a class="dropdown-item has-text-warning" href="{% url 'vk:hidden_post' pk=k.id %}">
                  <span class="icon is-small">
                    <i class="fas fa-eye-slash"></i>
                  </span>
                  Скрыть
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="message-body">
        <p class="first-letter">{{ k.text_post }}</p>
        {% if not k.link_image_post == "No image" %}
        <div class="message-image">
          <img src={{ k.link_image_post }} />
        </div>
        {% endif %}
      </div>
    </article>
  </div>
  {% endfor %}
</div>
{% endblock %}